# Generated by Django 4.2 on 2024-11-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_carrera_departamento_carreramateria'),
    ]

    operations = [
    ]
