# Generated by Django 4.2 on 2024-11-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_documentos_categoria_documentos_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
