# Generated by Django 4.2 on 2024-11-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_extencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='extencion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='Extencion', to='app.extencion'),
            preserve_default=False,
        ),
    ]
